### ISSUE TITLE
ACK After Authentication Required is not routed

### ISSUE THREAD

**Issue by haeferer** [davehorton/simple-sip-proxy#6]
Hi, 

now it works, at least the invite is correctly handled by our SIP Provider, except one Problem:

After the first INVITE the SIP Provider answers with an Authentication required. 
This is  answered with an new INVITE from the SIP Phone, containing the correct Authentication (works fine).

The first INVITE is answered by the phone with an ACK. This ACK is not handled by the proxy, so the
Sip Provider Repeats the "Authentication required" a few times (witch is not a show-stopper, but an error).
 
How we can proxy the ACK to the SIP Provider?

Cu 

Andreas

**Comment by davehorton** [comment]
hmm, that is strange.  Could you copy the full drachtio log into a gist and give me a link (feel free to send the link directly to me if you prefer at daveh at beachdognet dot com)

**Comment by haeferer** [comment]
pm is on the way

**Comment by haeferer** [comment]
PS: Also interessting: 
Within Wireshark you still see some TCP SYNC trying to establish a TCP connection to our SIP Provider (which still failes..) Maybe this is the ACK on the "wrong way" ?

**Comment by davehorton** [comment]
thats interesting, when you get a chance can you retest and turn drachtio log levels to debug, and also send me the pcap file?

**Comment by haeferer** [comment]
Jup,

Tomorrow as soon as I can try a next test



Von meinem iPhone gesendet

Am 12.11.2018 um 16:56 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


thats interesting, when you get a chance can you retest and turn drachtio log levels to debug, and also send me the pcap file?

**Comment by haeferer** [comment]
I had activated log debug and sofia log

this is the incoming ACK 

```
2018-11-13 09:58:01.141583 tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x1cb48b0): events IN
2018-11-13 09:58:01.141690 tport.c:2892 tport_recv_event() tport_recv_event(0x1cb48b0)
2018-11-13 09:58:01.141995 tport.c:3233 tport_recv_iovec() tport_recv_iovec(0x1cb48b0) msg 0x1cbf0f0 from (udp/172.17.0.2:5060) has 355 bytes, veclen = 1
2018-11-13 09:58:01.142168 recv 355 bytes from udp/[172.17.0.1]:39553 at 09:58:01.142074:

vvvvvv  shouldn't this "ACK" be forewarded to calling phone? vvvvvv

ACK sip:01520xxxxxx@sip.solucon.com:5070 SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5060;branch=z9hG4bK80da2d4698e5e8119f8be2e5316b3a5d;rport
From: <sip:fo281943tr34752_04@sip.solucon.com>;tag=2221240134
To: <sip:01520xxxxxx@sip.solucon.com:5070>;tag=Xtv376FBBa1jK
Call-ID: 80DA2D46-98E5-E811-9F8A-E2E5316B3A5D@127.0.0.1
CSeq: 11 ACK
Content-Length: 0

2018-11-13 09:58:01.142203 tport.c:3051 tport_deliver() tport_deliver(0x1cb48b0): msg 0x1cbf0f0 (355 bytes) from udp/172.17.0.1:5060 next=(nil)
2018-11-13 09:58:01.142230 nta.c:2968 agent_recv_request() nta: received ACK sip:01520xxxxxx@sip.solucon.com:5070 SIP/2.0 (CSeq 11)
2018-11-13 09:58:01.142255 nta.c:3263 agent_check_request_via() nta: Via check: received=172.17.0.1
2018-11-13 09:58:01.142282 nta.c:3183 agent_recv_request() nta: ACK (11) to message callback
2018-11-13 09:58:01.142301 processMessageStatelessly - incoming message with call-id 80DA2D46-98E5-E811-9F8A-E2E5316B3A5D@127.0.0.1 does not match an existing call leg, processed in thread 7f7393f42780
```


###  does not match an existing call leg, processed in thread

**Comment by haeferer** [comment]
https://gist.github.com/haeferer/56e232208925286ba4e1d940544b6f41

**Comment by davehorton** [comment]
you are right - the server is trying to send the ACK via tcp for some reason.  I will look into this further, and I should be able to recreate and produce a fix.  In the meantime, you may want to simply exclude tcp if you dont have any endpoints requiring it, i.e. `--contact "sip:*;transport=udp"` instead of `udp,tcp`

**Comment by davehorton** [comment]
Also, I should have an update for this project to move it to the latest drachtio-srf by tomorrow

**Comment by haeferer** [comment]
Perfect, `` --contact "sip:*;transport=udp" `` as a workaround works.
Now ACK is routed correctly to our Provider. 

:) Great :+1:

**Comment by haeferer** [comment]
PS: Maybe the Bug is based on our configuration. 
DrachtIO Server is configured to run on 5070, not on 5060. So the SipPhone calls with a different SIP Port !

**Comment by davehorton** [comment]
No, it is definitely a bug on my side.  Are you building from source, or using a docker image?  If from source, I could give you a patch to test, if docker I could build you an image.  Let me know if you are willing to test a patch..

**Comment by haeferer** [comment]
Currently we are simply using the docker image (drachtio/drachtio-server:latest)
Building from source is not an easy task for today. sorry :(

**Comment by davehorton** [comment]
I think that another workaround might be to switch the order of protocols, e.g
```
--contact "sip:*;transport=udp,tcp"
```
instead of 
```
--contact "sip:*;transport=tcp,udp"
```
That way, I think both are supported but UDP would be attempted first (I think) for the ACK.

Meanwhile I am still looking at a proper fix

**Comment by haeferer** [comment]
ok we will try this tomorrow

**Comment by davehorton** [comment]
I've actually built a docker image with an attempted fix.  If you could try the "drachtio/drachtio-server:edge" image tomorrow with your original configuration, that would be great.  (Note: it hasnt finished building yet, but should be there tomorrow)

**Comment by haeferer** [comment]
Great, we will try tomorrow

Von meinem iPhone gesendet

Am 13.11.2018 um 16:05 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


I've actually built a docker image with an attempted fix. If you could try the "drachtio/drachtio-server:edge" image tomorrow with your original configuration, that would be great. (Note: it hasnt finished building yet, but should be there tomorrow)

**Comment by haeferer** [comment]
Patch works. 

Thx
