### ISSUE TITLE
BYE is not passed back to the caller

### ISSUE THREAD

**Issue by ttitze2** [davehorton/simple-sip-proxy#7]
Hello Dave,

I tested the  edge-release of simple-sip-proxy-server.
The issue "ACK after Authentication" recently launched 
by my colleague Andreas is solved. 
Thanks a lot for the immediate fix!

But there is still similar problem when 
the phone call is terminated by the called phone.

The BYE event will not be returned to the calling phone
which will remain in the connected mode forever.

You will find this behaviour in the attached log-file.

I would be happy if you could have a look at that.

Kind Regards

Thomas Titze

[BYE_EventHandling.txt](https://github.com/davehorton/simple-sip-proxy/files/2580343/BYE_EventHandling.txt)

**Comment by davehorton** [comment]
In this case it appears to be an issue with your SIP client.

Note that you did not add a Record-Route header to the proxied INVITE, and thus the BYE should not be sent through the proxy.  It should instead have been sent to freeswitch server at sip:015208510550@92.197.180.227:5060.  Therefore, when the proxy gets the BYE, it returns a 481.

**Comment by ttitze2** [comment]
Hi Dave,

in the case the calling phone terminates the call it works at the first glance -- the called phone hangs up correctly. The inspection of the log-file shows that the CANCEL-Event will not be passed through to the caller:

2018-11-14 12:37:05.279055 tport.c:3233 tport_recv_iovec() tport_recv_iovec(0xffe9d0) msg 0x1006ef0 from (udp/172.17.0.2:5060) has 874 bytes, veclen = 1
2018-11-14 12:37:05.279369 recv 874 bytes from udp/[172.17.0.1]:41593 at 12:37:05.279165:
CANCEL sip:015208510550@sip.solucon.com:5070 SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5060;branch=z9hG4bK80ba7da477e6e811b557f56c9568ac6a;rport
From: <sip:fo281943tr34752_04@sip.solucon.com>;tag=3537221417
To: <sip:015208510550@sip.solucon.com:5070>
Call-ID: 0024E5A3-77E6-E811-B555-F56C9568AC6A@127.0.0.1
CSeq: 23 CANCEL
Contact: <sip:fo281943tr34752_04@127.0.0.1:5060;gr=00B9E07E-57E6-E811-B53B-F56C9568AC6A>
Proxy-Authorization: Digest username="fo281943tr34752_04", realm="sip.solucon.com", nonce="f953d77c-e809-11e8-ac2c-a77d12d8702e", uri="sip:015208510550@sip.solucon.com:5070", response="7c19ec24d77eb87bbc87363446d0979e", algorithm=MD5, cnonce="806e42a977e6e811b557f56c9568ac6a", qop=auth, nc=00000002
Allow: INVITE, ACK, BYE, CANCEL, INFO, MESSAGE, NOTIFY, OPTIONS, REFER, UPDATE, PRACK
Max-Forwards: 70
User-Agent: SIPPER for PhonerLite
Content-Length: 0

2018-11-14 12:37:05.279548 tport.c:3051 tport_deliver() tport_deliver(0xffe9d0): msg 0x1006ef0 (874 bytes) from udp/172.17.0.1:5060 next=(nil)
2018-11-14 12:37:05.280250 nta.c:2968 agent_recv_request() nta: received CANCEL sip:015208510550@sip.solucon.com:5070 SIP/2.0 (CSeq 23)
2018-11-14 12:37:05.280468 nta.c:3263 agent_check_request_via() nta: Via check: received=172.17.0.1
2018-11-14 12:37:05.280719 nta.c:3183 agent_recv_request() nta: CANCEL (23) to message callback
2018-11-14 12:37:05.280995 processMessageStatelessly - incoming message with call-id 0024E5A3-77E6-E811-B555-F56C9568AC6A@127.0.0.1 does not match an existing call leg, processed in thread 7f7f367f3780
2018-11-14 12:37:05.281090 tport.c:3285 tport_tsend() tport_tsend(0xffe9d0) tpn = UDP/172.17.0.1:41593
2018-11-14 12:37:05.281197 tport.c:4085 tport_resolve() tport_resolve addrinfo = 172.17.0.1:41593
2018-11-14 12:37:05.281509 tport.c:3531 tport_send_msg() tport_vsend returned 349
2018-11-14 12:37:05.281929 send 349 bytes to udp/[172.17.0.1]:41593 at 12:37:05.281328:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 127.0.0.1:5060;branch=z9hG4bK80ba7da477e6e811b557f56c9568ac6a;rport=41593;received=172.17.0.1
From: <sip:fo281943tr34752_04@sip.solucon.com>;tag=3537221417
To: <sip:015208510550@sip.solucon.com:5070>;tag=Q8e5p6tNeD65S
Call-ID: 0024E5A3-77E6-E811-B555-F56C9568AC6A@127.0.0.1
CSeq: 23 CANCEL
Content-Length: 0

I suppose that this is the same problem.

Kind Regards,

Thomas

**Comment by davehorton** [comment]
Actually, I'm sorry I misread and did not understand that the BYE is coming from the Freeswitch.  Nonetheless, the problem appears to be that since there is no Record-Route header, the Freeswitch should have sent the BYE to the Contact header in the INVITE, which is the UAC client.  I will look into this on the Freeswitch side, because to my knowledge Freeswitch should not have this bug.

As far as the CANCEL, though, that is a different situation, and the CANCEL *should* traverse the proxy.  Could you send me a gist of a full drachtio log showing the CANCEL?

**Comment by davehorton** [comment]
I am thinking the BYE issue may have something to do with your nat situation since freeswitch is putting the correct URI in the BYE (BYE sip:fo281943tr34752_04@127.0.0.1:5060) but is sending to the proxy.

This implies to me that Freeswitch is set up to enable nat detection, and is going to send back to the proximate server that sent to it -- which is the proxy.

Also, since the UA client is using 127.0.0.1 (ie localhost) as its IP, it will not be reachable from the freeswitch anyways.  If you want to do a real-world type of test I think you need to have a UA client listening on an a non-localhost address.

You have a couple of choices:
1.  Move the UAC client to an actual network address (not localhost) and configure the freeswitch to not do nat detection.
2.  Leave everything as is, but change the simple-sip-proxy app to add a Record-Route header (`opts.recordRoute` per https://drachtio.org/api#sip-request-proxy).

**Comment by davehorton** [comment]
were you able to try either of the above suggestions?  Also, I realized that since you are using an older version of the framework you may need to use `opts.remainInDialog` rather than `opts.recordRoute`

**Comment by ttitze2** [comment]
Hi Dave,
Thanks for this clue! 
I searched for an option like "recordRoute" in vain. The Option remainInDialog was set to false.

 After a quick test it obviously works: If set to true, the caller hangs up when the called phone sends "Bye". I'll test it more thoroughly.

Unfortunately I cannot test the other proposition because I don't have a public IP address at the moment.

I'll close the issue for now. 

In case of need I'll come back to you.

Kind Regards,

Thomas

**Comment by davehorton** [comment]
OK, is there still an issue with the CANCEL scenario (i.e. caller hangs up before call is answered)?

**Comment by ttitze2** [comment]
Yes! This problem still exists. The call will not be cancelled/terminated if the called phone rejects the call. 
I only found the following hint of a CANCEL Event in the log file:

vvvvvvvvvvvvvvvvv
2018-11-15 13:45:14.831818 ClientTransaction::cancelRequest - returning without canceling because state is not PROCEEDING it is TERMINATED
2018-11-15 13:45:14.831878 ProxyCore::removeTerminated: removeTerminated - removed 1 client transactions, leaving 0
2018-11-15 13:45:14.831926 ProxyCore::removeTerminated: removeTerminated - all client TUs are terminated, removing proxy core
2018-11-15 13:45:14.831982 SipProxyController::removeProxyByCallId - there are now 1 proxy instances
2018-11-15 13:45:14.832052 No connected clients found to handle incoming cdr:start request
^^^^^^^^^^^^

But the caller obviously missed it.

**Comment by davehorton** [comment]
can you give me a link to a gist of the entire drachtio log for this call?

**Comment by ttitze2** [comment]
The call was initiated at 13:45 and cancelled after a few rings.


see attached file
[SimSipServLog(4).txt](https://github.com/davehorton/simple-sip-proxy/files/2585610/SimSipServLog.4.txt)

**Comment by davehorton** [comment]
Hmm, the CANCEL never arrives to drachtio, so the client must have sent it elsewhere.  Can you get a pcap from the client device to see where it is sending the CANCEL?

(Those messages you cited are just indicating that the client transaction was successful now that a 200 OK was received from the UA server)

**Comment by ttitze2** [comment]
I just had a discussion with my colleague about this topic. 
He explained to me that refusion by the called phone is neither
 a "termination" nor a "cancel".

So this behaviour is not a bug.
The caller normally should not discern whether the callee refuses the call or whether he/she is unavailable.

I'll close this issue.

**Comment by davehorton** [comment]
OK, but it does not sound normal to me.  What I saw in the log is that the called phone started ringing after 3 seconds.  10 seconds after that it was answered.  I did not see a BYE in the log at all.  So if the caller hung up while the phone was ringing for those 10 seconds, we should have seen the calling endpoint send a CANCEL request through the proxy.

**Comment by ttitze2** [comment]
… not the caller hung up, the called phone refused the call. This case is neither a
cancel nor a bye. There is no phone call established, so there is nothing to do!
That's OK.

If the caller cancels his call everything works fine, too.

**Comment by davehorton** [comment]
ok, I agree with that statement above.....however that last log file showed a call that was accepted, not rejected.  I'll assume for that that was a different call than the scenario you are describing, and leave the issue closed...
